version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ${NGINX_CONFIG}:/etc/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      backend:

  php-fpm:
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php-fpm
    volumes:
      - ${WEB_ROOT}:/var/www/html/
      - ${PHP_CONFIG}:/usr/local/etc
    restart: always
    networks:
      backend:
    depends_on:
      - mysql
      - nginx
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${MYSQL_TZ}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      backend:
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      backend:

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      backend:
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    restart: always
    depends_on:
      - php-fpm
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - ${OFELIA_CONFIG}:/etc/ofelia/config.ini
    networks:
      backend:

volumes:
  mysql:

networks:
  backend:
    driver: bridge
